// supabase/functions/create_profile/index.ts
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

type Role = "client" | "trainer" | "admin";

function calcBmi(weightKg: number, heightCm: number) {
  if (!weightKg || !heightCm || heightCm <= 0) {
    return { bmi: null, status: null };
  }
  const h = heightCm / 100;
  const bmi = weightKg / (h * h);
  let status: string;
  if (bmi < 18.5) status = "underweight";
  else if (bmi < 25) status = "normal";
  else if (bmi < 30) status = "overweight";
  else status = "obese";
  return { bmi: Number(bmi.toFixed(1)), status };
}

Deno.serve(async (req) => {
  try {
    if (req.method !== "POST") {
      return new Response(JSON.stringify({ error: "Method not allowed" }), { 
        status: 405,
        headers: { "Content-Type": "application/json" }
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const admin = createClient(supabaseUrl, serviceRoleKey, {
      auth: {
        autoRefreshToken: false,
        persistSession: false
      }
    });

    const {
      auth_user_id,
      email,
      user_id, // your "User ID" handle used for search (like gopi_5412)
      first_name,
      last_name,
      phone,
      height_cm,
      weight_kg,
      role,
      category, // primary category (required in schema)
      categories, // array of categories
      dob, // date of birth (ISO string or YYYY-MM-DD)
      years_experience,
      trainer_specialties,
    } = await req.json();

    // Validate required fields
    if (!auth_user_id || !email || !user_id || !first_name || !last_name || !phone || !height_cm || !weight_kg || !role) {
      return new Response(
        JSON.stringify({ error: "Missing required fields", detail: "All fields are required" }), 
        { 
          status: 400,
          headers: { "Content-Type": "application/json" }
        }
      );
    }

    // Ensure category is provided (required in schema)
    const primaryCategory = category || (categories && categories.length > 0 ? categories[0] : 'general');

    const r: Role = role;

    // Calculate BMI
    const { bmi, status } = calcBmi(Number(weight_kg), Number(height_cm));

    // 1) Insert profile (display_name is auto-generated by database)
    const { error: profileErr, data: profileData } = await admin
      .from("profiles")
      .insert({
        id: auth_user_id,
        user_id: user_id, // unique user handle
        email: email.toLowerCase(),
        first_name: first_name.trim(),
        last_name: last_name.trim(),
        phone: phone.trim(),
        height_cm: Number(height_cm),
        weight_kg: Number(weight_kg),
        bmi: bmi,
        bmi_status: status,
        role: r,
        category: primaryCategory, // primary category (required)
        categories: categories || [], // array of categories
        dob: dob || null, // date of birth (DATE format: YYYY-MM-DD)
        avatar_path: null,
        cover_path: null,
      })
      .select()
      .single();

    if (profileErr) {
      console.error("Profile insert error:", profileErr);
      // Check for unique constraint violations
      if (profileErr.message.includes("profiles_user_id_unique") || profileErr.message.includes("user_id")) {
        return new Response(
          JSON.stringify({ error: "Username already taken", detail: "The chosen username is already in use" }), 
          { 
            status: 409,
            headers: { "Content-Type": "application/json" }
          }
        );
      }
      if (profileErr.message.includes("profiles_email_unique") || profileErr.message.includes("email")) {
        return new Response(
          JSON.stringify({ error: "Email already exists", detail: "An account with this email already exists" }), 
          { 
            status: 409,
            headers: { "Content-Type": "application/json" }
          }
        );
      }
      return new Response(
        JSON.stringify({ error: "Profile insert failed", detail: profileErr.message }), 
        { 
          status: 400,
          headers: { "Content-Type": "application/json" }
        }
      );
    }

    // 2) If trainer, insert trainer_profiles row
    if (r === "trainer") {
      const { error: trainerErr } = await admin
        .from("trainer_profiles")
        .insert({
          user_id: auth_user_id,
          years_experience: years_experience ? Number(years_experience) : null,
          specialties: trainer_specialties || categories || [],
          verified: false,
        });

      if (trainerErr) {
        console.error("Trainer profile insert error:", trainerErr);
        // Don't fail the whole signup if trainer profile fails, but log it
        // The profile was created successfully, trainer profile can be added later
        return new Response(
          JSON.stringify({ 
            ok: true, 
            warning: "Profile created but trainer profile failed",
            detail: trainerErr.message,
            bmi, 
            bmi_status: status 
          }), 
          {
            headers: { "Content-Type": "application/json" },
            status: 200,
          }
        );
      }

      // Optional: Create pending verification entry
      try {
        await admin.from("trainer_verifications").insert({
          trainer_id: auth_user_id,
          status: "pending",
        });
      } catch (verificationErr) {
        // Non-critical, just log
        console.warn("Trainer verification insert failed:", verificationErr);
      }
    }

    return new Response(
      JSON.stringify({ 
        ok: true, 
        bmi, 
        bmi_status: status,
        profile_id: auth_user_id
      }), 
      {
        headers: { "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (e) {
    console.error("Unexpected error in create_profile:", e);
    return new Response(
      JSON.stringify({ error: "Unexpected error", detail: String(e) }), 
      {
        headers: { "Content-Type": "application/json" },
        status: 500,
      }
    );
  }
});

